// GENERATED by tools/gen-core-fixtures.mjs from the src/ assembler. Do not edit by hand;
// run `node tools/gen-core-fixtures.mjs --write` to regenerate. See tools/core-fixture.mjs.
#ifndef C64_FIXTURE_BORDER_BG_HPP
#define C64_FIXTURE_BORDER_BG_HPP

#include <cstdint>

namespace c64_fixture {

// Direct-mode PRG: 2-byte load address followed by code that sets $D020/$D021 then spins.
inline constexpr std::uint8_t kBorderBgPrg[] = {
    0x00, 0xc0, 0xa9, 0x02, 0x8d, 0x20, 0xd0, 0xa9, 0x06, 0x8d, 0x21, 0xd0,
    0x4c, 0x0a, 0xc0,
};

inline constexpr std::uint16_t kBorderBgLoadAddress = 0xc000;
inline constexpr std::uint16_t kBorderBgRunAddress = 0xc000;
inline constexpr std::uint8_t kExpectedBorder = 0x02;
inline constexpr std::uint8_t kExpectedBackground = 0x06;
inline constexpr std::uint16_t kFrameWidth = 384;
inline constexpr std::uint16_t kFrameHeight = 272;
inline constexpr int kBorderSampleIndex = 0;
inline constexpr int kCentreSampleIndex = 52416;

} // namespace c64_fixture

#endif // C64_FIXTURE_BORDER_BG_HPP
